
/*
 * Warning.
 * Do not edit this file.  It is generated from dataapps.yaml
 * ...edit that file instead.
 */

var json = {
  "id": 0, 
  "data": {
    "description": "This is a landing page for Fedora teams.  The Fedora community is <em>huge</em>; this page details the teams that make each Fedora release!  Explore!\n"
  }, 
  "name": "Fedora community teams", 
  "children": [
    {
      "id": 1, 
      "data": {
        "description": "These thoughtful communicators write manuals, guides, blogs posts, articles and more!\n"
      }, 
      "name": "Content writing", 
      "children": [
        {
          "data": {
            "url": "https://fedoraproject.org/wiki/Artwork", 
            "description": "Write tutorials and articles for the use of the FOSS creative  tools available in Fedora. \n"
          }, 
          "name": "Artwork", 
          "id": 2
        }, 
        {
          "data": {
            "url": "https://fedoraproject.org/wiki/DocsProject", 
            "description": "Write documents, guides, how-tos, FAQs, marketing material,  process/methodology docs, release notes. Write content in the knowledgebase (kbase) and on the Wiki. \n"
          }, 
          "name": "Docs", 
          "id": 3
        }, 
        {
          "data": {
            "url": "https://fedoraproject.org/wiki/NewsProject", 
            "description": "Write content for the Fedora weekly magazine!\n"
          }, 
          "name": "News", 
          "id": 4
        }, 
        {
          "data": {
            "url": "https://fedoraproject.org/wiki/Category:Fonts_SIG", 
            "description": "Document various fonts, best practices, and a lot more!\n"
          }, 
          "name": "Fonts SIG", 
          "id": 5
        }, 
        {
          "data": {
            "url": "https://fedoraproject.org/wiki/SIGs/Games", 
            "description": "Document the available games, including wiki documentation and listing in comps.xml. \n"
          }, 
          "name": "Games SIG", 
          "id": 6
        }, 
        {
          "data": {
            "url": "https://fedoraproject.org/wiki/Usability", 
            "description": "write documentation about usability. \n"
          }, 
          "name": "Usability SIG", 
          "id": 7
        }
      ]
    }, 
    {
      "id": 8, 
      "data": {
        "description": "Communicate through images\n"
      }, 
      "name": "Designer", 
      "children": [
        {
          "data": {
            "url": "https://fedoraproject.org/wiki/Design", 
            "description": "Serve as a part of a design firm for the Fedora community, creating  artwork and designs to for the Fedora community on request.  Design projects including Fedora Logo, MarketingCollateral, PromoBanners,  Widgets, Theming Overview, Bluecurve Icon Theme, Echo Icon Theme,  MediaArt, SoC Posters, T-Shirt Design, Media Gallery\n"
          }, 
          "name": "Design", 
          "id": 9
        }, 
        {
          "data": {
            "url": "https://fedoraproject.org/wiki/Category:Fonts_SIG", 
            "description": "Find the best fonts to include, to please artists Identify font creation tools that need packaging Create and improve Fedora fonts Propose good default fonts\n"
          }, 
          "name": "Fonts SIG", 
          "id": 10
        }, 
        {
          "data": {
            "url": "https://fedoraproject.org/wiki/Usability", 
            "description": "Improve end-user experience with coherent, accessible and intuitive design for Fedora. \n"
          }, 
          "name": "Usability SIG", 
          "id": 11
        }
      ]
    }, 
    {
      "id": 12, 
      "data": {
        "description": "Communicate through code\n"
      }, 
      "name": "OS Developer", 
      "children": [
        {
          "data": {
            "url": "https://fedoraproject.org/wiki/BugZappers", 
            "description": "Track down and shoot Fedora bugs in bugzilla.redhat.com.  Strive to be a bridge between users and developers that aids in fixing and closing bugs. \n"
          }, 
          "name": "Bug triage", 
          "id": 13
        }, 
        {
          "data": {
            "url": "https://fedoraproject.org/wiki/Infrastructure", 
            "description": "Help to provide servers, tools and utilities for the Fedora Project. Create new applications to make development of Fedora go smoother. \n"
          }, 
          "name": "Infrastructure", 
          "id": 14
        }, 
        {
          "data": {
            "url": "https://fedoraproject.org/wiki/ReleaseEngineering", 
            "description": "Manage the build system Maintain package repositories Create the images for new Fedora releases\n"
          }, 
          "name": "Release Engineering", 
          "id": 15
        }, 
        {
          "data": {
            "url": "https://fedoraproject.org/wiki/I18N", 
            "description": "Develop, package, and maintain applications like input methods for different languages.  Improve applications and utilities to support and process different languages.  Quality-assure that existing applications meet i18n standards.  Support the infrastructure of the Fedora translation community. \n"
          }, 
          "name": "Internationalization (i18n)", 
          "id": 16
        }, 
        {
          "data": {
            "url": "https://fedoraproject.org/wiki/PackageMaintainers/Join", 
            "description": "Become a package maintainer to create and maintain RPM packages for software in Fedora.  Join the Package Review SIG\n"
          }, 
          "name": "Packaging", 
          "id": 17
        }, 
        {
          "data": {
            "url": "https://fedoraproject.org/wiki/Websites", 
            "description": "Improve Fedoras image and create the best possible interface for users and contributors on the Internet\n"
          }, 
          "name": "Websites", 
          "id": 18
        }
      ]
    }
  ]
}
